apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # k files
build:
  local:
    push: false # do not push to dockerhub when file change
  artifacts:
    - image: netogerbi/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netogerbi/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "**/*.ts"
            dest: .
    - image: netogerbi/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netogerbi/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netogerbi/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netogerbi/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync: # watch file changes
        manual:
          - src: "src/**/*.ts"
            dest: .
