apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl
spec:
  replicas: 1
  selector: #how to refer the pod inside cluster
    matchLabels:
      app: expiration-redis
  template: # how the pod must be created
    metadata:
      labels:
        app: expiration-redis
    spec: # tells the pod how to behave
      containers:
        - name: expiration-redis # logging porpouses
          image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-srv
spec:
  selector:
    app: expiration-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
