apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector: #how to refer the pod inside cluster
    matchLabels:
      app: orders-mongo
  template: # how the pod must be created
    metadata:
      labels:
        app: orders-mongo
    spec: # tells the pod how to behave
      containers:
        - name: orders-mongo # logging porpouses
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
